/* Generated By:JavaCC: Do not edit this line. jccConstants.java */
package Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface jccConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int L = 5;
  /** RegularExpression Id. */
  int May = 6;
  /** RegularExpression Id. */
  int Min = 7;
  /** RegularExpression Id. */
  int D = 8;
  /** RegularExpression Id. */
  int gb = 9;
  /** RegularExpression Id. */
  int S = 10;
  /** RegularExpression Id. */
  int Expresion = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<L>",
    "<May>",
    "<Min>",
    "<D>",
    "<gb>",
    "<S>",
    "<Expresion>",
  };

}
